// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "production";
	OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1";
	COACH_DO: DurableObjectNamespace<import("./src/index").CoachDurable>;
	IMAGES: R2Bucket;
	ASSETS: Fetcher;
}
